version: 2.2.3
synopsis: A Testing Framework for Haskell
description: >
  This package exposes internal types and functions that can be used to extend
  Hspec's functionality.
license: MIT
copyright:
  - (c) 2011-2015 Simon Hengel
  - (c) 2011-2012 Trystan Spangler
  - (c) 2011 Greg Weber
maintainer: Simon Hengel <sol@typeful.net>
category: Testing
stability: experimental
homepage: http://hspec.github.io/

github: hspec/hspec/hspec-core

ghc-options: -Wall

dependencies:
  - base >= 4.3 && < 5
  - random
  - tf-random
  - setenv
  - ansi-terminal >= 0.5
  - time
  - transformers >= 0.2.2.0
  - deepseq
  - name: HUnit
    github: hspec/HUnit
    ref: failure-type
  - QuickCheck >= 2.5.1
  - name: quickcheck-io
    github: sol/quickcheck-io
    ref: hunit-1.4
  - name: hspec-expectations
    github: hspec/hspec-expectations
    ref: diff-support
  - async >= 2
  - array

library:
  source-dirs: src
  exposed-modules:
    - Test.Hspec.Core.Spec
    - Test.Hspec.Core.Hooks
    - Test.Hspec.Core.Runner
    - Test.Hspec.Core.Formatters
    - Test.Hspec.Core.QuickCheck
    - Test.Hspec.Core.Util

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - name: hspec-meta
        github: hspec/hspec
        ref: 88b2bb0de6b85947bb928b9241ffaa964aa80968
      - silently >= 1.2.4
      - process
